# Cargo.toml
[package]
name = "veko_dome"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json", "socks"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
log = "0.4"
simple_logger = "4.0"
trust-dns-resolver = "0.22"
ctrlc = "3.2"
fastrand = "1.8"
